allprojects {
    group = "io.github.spencerpark"
    version = "1.5.0"

    repositories {
        maven { url = 'https://maven.aliyun.com/repository/public/' }
        maven { url = 'https://maven.aliyun.com/repository/central' }
        maven { url = 'https://repository.apache.org/content/repositories/releases' }
        gradlePluginPortal()
        mavenCentral()

        mavenLocal()
    }

    apply(plugin: 'java')
}

subprojects {
    apply(plugin: 'jvm-test-suite')

    dependencies {
        // Logging
        implementation(libs.bundles.logging)

        // Testing
        testImplementation(libs.bundles.tests)
    }

    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(17))
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.compilerArgs.add("-parameters")
        options.compilerArgs.add("-Xlint:deprecation")
    }

    testing {
        suites {
            test {
                useJUnitJupiter()
            }
        }
    }
}
