import com.github.jk1.license.filter.LicenseBundleNormalizer
import com.github.jk1.license.render.InventoryHtmlReportRenderer
import com.github.jk1.license.render.JsonReportRenderer
import org.apache.tools.ant.filters.ReplaceTokens

plugins {
    id 'application'
    alias(libs.plugins.shadowJar)
    alias(libs.plugins.lombok)

    id 'com.github.hierynomus.license' version '0.16.1'
    id "com.github.jk1.dependency-license-report" version "2.1"
}

dependencies {
    implementation(project(":jupyter-jvm-basekernel"))
    implementation(libs.gson)

    implementation(libs.bundles.maven)
}

// Add the license header to source files
license {
    header = file('LICENSE')
    include "**/*.java"
    exclude "**/Test*.java"
    mapping java: 'SLASHSTAR_STYLE'
    ext.year = Calendar.getInstance().get(Calendar.YEAR)
}
licenseMain.dependsOn 'licenseFormat'

// replace @symbol@ in properties
processResources {
    def tokens = [
            'version': project.version,
            'project': project.name
    ]
    inputs.properties(tokens)
    filter tokens: tokens, ReplaceTokens
}

//java {
//    withJavadocJar()
//    withSourcesJar()
//}

application {
    mainClass = 'io.github.spencerpark.ijava.IJava'
}

tasks.jar {
    manifest {
        attributes["Main-Class"] = application.mainClass.get()
    }
}

// shadow Jar config
tasks.shadowJar {
    enableRelocation = true
    relocationPrefix = "io.github.spencerpark.shaded"
    // copy build.gradle to shadowed jar
    from("./build.gradle")
}

// create license report
licenseReport {
    renderers = [
            new InventoryHtmlReportRenderer('license-report.html'),
            new JsonReportRenderer('license-report.json')
    ]

    filters = [new LicenseBundleNormalizer()]
}

// pack up
tasks.register('packDist', Zip) {
    archiveFileName = project.name + "-latest.zip"

    from(layout.buildDirectory.dir("resources/main")) {
        include "install.py"
    }

    from(layout.buildDirectory.dir("libs")) {
        include "*-all.jar"
        into "java"
    }

    from(layout.buildDirectory.dir("resources/main")) {
        include "kernel.json"
        into "java"
    }

    from(layout.buildDirectory.dir("reports/dependency-license")) {
        into "java/dependency-license"
    }

    dependsOn generateLicenseReport
    dependsOn shadowJar
}
